sidekiq:
  redis:
    host: <%= ENV["SIDEKIQ_REDIS_HOST"] || 'redis' %>
    port: <%= ENV["SIDEKIQ_REDIS_PORT"] || 6379 %>
    password: <%= ENV["SIDEKIQ_REDIS_PASSWORD"] || '' %>

oss:
  path: <%= File.join(Rails.root, 'storage') %>
